### ISSUE TITLE
Right Pop-out menu not optimized for shorter screens

### ISSUE THREAD

**Issue by gthaka** [DevHumbleChris/nuxt-github-clone#1]
My viewport is `775px` and I can only see the sign out option after zooming out. The scroll bar present (in screenshot) is for the page view,

**Expected**:- The menu should have a scrollbar to scroll down to the last menu item (Sign Out), which I was trying to get to.

See screenshot below:-

![image](https://github.com/DevHumbleChris/nuxt-github-clone/assets/6692971/6247515e-78e7-4d59-8920-4f47fa5be1cd)

#awesomeproject

**Comment by thecodingmontana** [comment]
Working on the fix. Thanks @gthaka
