### ISSUE TITLE
Both left-right menus active

### ISSUE THREAD

**Issue by gthaka** [DevHumbleChris/nuxt-github-clone#2]
The left and right pop-out menus are both shown when they are clicked simultaneously.

**Expected**: - Just like GitHub; the menus are only active one at a time, never both.

See screenshot below

![image](https://github.com/DevHumbleChris/nuxt-github-clone/assets/6692971/f383b9a7-e732-4572-9223-1840e9247cd7)

Keep up the good work 💪🏽

**Comment by thecodingmontana** [comment]
Thanks for the feedback. Working on the fix
